name: "build-docker-images"
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/build-docker-images.yml"
      - ".github/docker-compose.yml"
      - "contrib/docker/Dockerfile"
      - "lib/*.ps1"
  workflow_dispatch:
env:
  DOCKER_BUILDKIT: 0
defaults:
  run:
    working-directory: .github
jobs:
  nanoserver:
    name: "build and push nanoserver docker image"
    runs-on: windows-latest
    steps:
      - name: "docker path"
        run: "where docker"
        shell: "cmd"
      - name: "use windows containers engine"
        run: |
          & ( '{0}\Docker\Docker\DockerCli.exe' -f $Env:ProgramFiles ) -SwitchWindowsEngine
      - name: "pull image"
        run: >
          docker pull mcr.microsoft.com/windows/nanoserver:20H2
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: "build docker image"
        env:
          USER: code
        run: >
          docker-compose 
          build 
          --build-arg "user=$Env:USER"
          pwsh-nanoserver
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "push docker image"
        run: >
          docker-compose
          push
          pwsh-nanoserver
  servercore:
    name: "build and push servercore docker image"
    runs-on: windows-latest
    steps:
      - name: "use windows containers engine"
        run: |
          & ( '{0}\Docker\Docker\DockerCli.exe' -f $Env:ProgramFiles ) -SwitchWindowsEngine
      - name: "pull image"
        run: >
          docker pull mcr.microsoft.com/windows/servercore:20H2
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: "build docker image"
        env:
          USER: code
        run: >
          docker-compose 
          build 
          --build-arg "user=$Env:USER"
          pwsh-servercore
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "push docker image"
        run: >
          docker-compose
          push
          pwsh-servercore
  windows:
    name: "build and push windows docker image"
    runs-on: windows-latest
    steps:
      - name: "use windows containers engine"
        run: |
          & ( '{0}\Docker\Docker\DockerCli.exe' -f $Env:ProgramFiles ) -SwitchWindowsEngine
      - name: "pull image"
        run: >
          docker pull mcr.microsoft.com/windows:20H2
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: "build docker image"
        env:
          USER: code
        run: >
          docker-compose 
          build 
          --build-arg "user=$Env:USER"
          pwsh-windows
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "push docker image"
        run: >
          docker-compose
          push
          pwsh-windows
