name: "build-docker-images"
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/build-docker-images.yml"
      - ".github/docker-compose.yml"
      - "contrib/docker/Dockerfile"
      - "lib/*.ps1"
  workflow_dispatch:
env:
  DOCKER_BUILDKIT: 0
jobs:
  nanoserver:
    name: "build and push nanoserver docker image"
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: "build docker image"
        env:
          USER: code
        working-directory: .github
        run: >
          docker-compose 
          build 
          --build-arg "user=$Env:USER"
          --build-arg "TAG=1809"
          pwsh-nanoserver
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "push docker image"
        working-directory: .github
        run: >
          docker-compose
          push
          pwsh-nanoserver
  servercore:
    name: "build and push servercore docker image"
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: "build docker image"
        env:
          USER: code
        working-directory: .github
        run: >
          docker-compose 
          build 
          --build-arg "user=$Env:USER"
          --build-arg "TAG=1809"
          pwsh-servercore
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "push docker image"
        working-directory: .github
        run: >
          docker-compose
          push
          pwsh-servercore
  windows:
    name: "build and push windows docker image"
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: "build docker image"
        env:
          USER: code
        working-directory: .github
        run: >
          docker-compose 
          build 
          --build-arg "user=$Env:USER"
          --build-arg "TAG=1809"
          pwsh-windows
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "push docker image"
        working-directory: .github
        run: >
          docker-compose
          push
          pwsh-windows
